// Category -> subcategory taxonomy for the parts inventory, loosely following
// Digi-Key's product categories.
//
// These strings are stored verbatim on each inventory row, so renaming or
// removing an existing entry orphans the parts that use it. Add freely;
// rename only alongside a data migration.
export const CATEGORY_OPTIONS = {
  Audio: [
    "Buzzer / Piezo",
    "Speaker",
    "Microphone",
    "Headphone / Earphone",
  ],
  Batteries: [
    "Coin Cell",
    "Li-Ion / LiPo",
    "Alkaline",
    "NiMH",
    "Battery Holder / Clip",
  ],
  Breakouts: [
    "Microcontroller",
    "SBC",
    "Power",
    "Sensor",
    "Audio",
    "Input",
    "Wireless",
    "Storage",
    "Display",
    "Motor Driver",
    "Communication / Interface",
    "Programmer / Debugger",
    "Evaluation Board",
    "Shield / HAT / Add-on",
  ],
  "Cables & Wires": [
    "Hook-up Wire",
    "Jumper Wire",
    "Ribbon / Flat Cable",
    "USB Cable",
    "Coaxial Cable",
    "Cable Assembly",
    "Heat Shrink",
  ],
  Capacitors: [
    "Ceramic / MLCC",
    "Film",
    "Tantalum",
    "Aluminum-Polymer",
    "Aluminum-Electrolytic",
    "Supercapacitor / EDLC",
    "Niobium Oxide",
    "Silicon",
    "Mica / PTFE",
    "Trimmer / Variable",
    "Network / Array",
  ],
  "Circuit Protection": [
    "Fuse - Chip / SMD",
    "Fuse - Cartridge / Through-hole",
    "PTC Resettable Fuse",
    "TVS Diode",
    "ESD Suppressor",
    "Varistor / MOV",
    "Gas Discharge Tube",
    "Inrush Current Limiter",
    "Fuse Holder",
  ],
  Connectors: [
    "USB",
    "2.54mm",
    "2.00mm",
    "1.27mm",
    "JST",
    "IC Socket",
    "FPC",
    "Audio",
    "Storage",
    "Terminal Block",
    "Barrel Jack",
    "RF / Coaxial",
    "Board-to-Board / Mezzanine",
    "Wire-to-Board",
    "Card Edge",
    "D-Sub",
    "RJ45 / Modular",
    "Pogo Pin / Spring Contact",
    "Crimp Contact / Housing",
  ],
  "Crystals & Oscillators": [
    "Crystal",
    "32.768 kHz Crystal",
    "Oscillator (XO)",
    "TCXO / VCXO",
    "MEMS Oscillator",
    "Ceramic Resonator",
  ],
  "Discrete Semiconductors": [
    "Diode - Rectifier",
    "Diode - Schottky",
    "Diode - Zener",
    "Diode - Small Signal",
    "Diode - Bridge Rectifier",
    "Diode - Varactor",
    "MOSFET - N-Channel",
    "MOSFET - P-Channel",
    "MOSFET - Array",
    "BJT - NPN",
    "BJT - PNP",
    "BJT - Array",
    "Digital / Pre-biased Transistor",
    "JFET",
    "IGBT",
    "Thyristor / TRIAC / SCR",
  ],
  Ferrites: ["Chip / SMD", "Through-hole", "Cable / Snap-on", "Array"],
  Filters: [
    "Common Mode Choke",
    "EMI / RFI Filter",
    "Feedthrough Capacitor",
    "SAW Filter",
    "Ceramic Filter",
  ],
  "Hardware & Fasteners": [
    "Standoff / Spacer",
    "Screw",
    "Nut",
    "Washer",
    "Heat-Set Insert",
    "Rubber Feet / Bumper",
    "Enclosure",
    "Knob",
  ],
  Inductors: [
    "Power - SMD",
    "Power - Through-hole",
    "RF / Signal",
    "Coupled",
    "Adjustable",
  ],
  "Integrated Circuit": [
    "PMIC",
    "LDO / Linear Regulator",
    "Buck Converter",
    "Boost Converter",
    "Buck-Boost Converter",
    "Battery Charger",
    "Battery Fuel Gauge / Protection",
    "Load Switch / Ideal Diode",
    "Voltage Reference",
    "Supervisor / Reset",
    "Op-Amp",
    "Comparator",
    "Instrumentation Amplifier",
    "Audio Amplifier",
    "Audio Codec",
    "DAC/ADC",
    "Sensor",
    "Logic - Gate",
    "Logic - Buffer / Driver",
    "Logic - Flip-Flop / Latch",
    "Logic - Shift Register",
    "Logic - Level Translator",
    "Analog Switch / Mux",
    "I/O Expander",
    "Interface - USB",
    "Interface - UART / RS-232 / RS-485",
    "Interface - CAN / LIN",
    "Interface - Ethernet",
    "Memory - EEPROM",
    "Memory - Flash",
    "Memory - SRAM / FRAM",
    "Clock / Timer / RTC",
    "Motor Driver",
    "Gate Driver",
    "LED Driver",
    "Display Driver",
    "Touch Controller",
    "FPGA / CPLD",
  ],
  Isolators: ["Optocoupler", "Digital Isolator", "Isolated Transceiver"],
  Microcontroller: [
    "AVR-8",
    "PIC-8",
    "PIC-16",
    "PIC-32",
    "8051",
    "MSP430",
    "ARM-M0",
    "ARM-M0+",
    "ARM-M3",
    "ARM-M23",
    "ARM-M33",
    "ARM-M4",
    "ARM-M7",
    "ARM-M55",
    "RISC-V",
    "RF / Wireless",
    "Microprocessor (MPU)",
  ],
  "Motors & Actuators": [
    "DC Motor",
    "Stepper Motor",
    "Servo",
    "Vibration Motor",
    "Solenoid",
  ],
  Optoelectronics: [
    "LED - Indicator (SMD)",
    "LED - Indicator (Through-hole)",
    "LED - RGB",
    "LED - Addressable",
    "LED - High Power",
    "LED - Infrared / UV",
    "Photodiode / Phototransistor",
    "Display - OLED",
    "Display - LCD Character",
    "Display - TFT",
    "Display - E-Paper",
    "Display - 7-Segment",
    "Light Pipe",
  ],
  Potentiometers: ["Rotary", "Slide", "Trimmer", "Thumbwheel"],
  "Power Supplies": [
    "DC-DC Module - Isolated",
    "DC-DC Module - Non-isolated",
    "AC-DC Module",
    "Wall Adapter / External",
  ],
  Prototyping: [
    "Breadboard",
    "Perfboard / Stripboard",
    "Adapter Board",
    "Test Point",
  ],
  Relays: [
    "Signal",
    "Power",
    "Solid State",
    "Reed",
    "Relay Socket",
  ],
  Resistors: [
    "Chip / SMD",
    "Through-hole",
    "Network / Array",
    "Current Sense / Shunt",
    "High Power / Chassis Mount",
  ],
  "RF & Wireless": [
    "Antenna - Chip",
    "Antenna - PCB / Flex",
    "Antenna - External",
    "Wi-Fi / Bluetooth Module",
    "LoRa / Sub-GHz Module",
    "GNSS / GPS Module",
    "RF Transceiver IC",
    "Balun",
    "RF Shield",
  ],
  Sensors: [
    "Temperature",
    "Humidity",
    "Pressure / Barometric",
    "IMU / Accelerometer / Gyro",
    "Magnetometer",
    "Hall Effect",
    "Current",
    "Light / Color",
    "Proximity / Time-of-Flight",
    "Gas / Air Quality",
    "Motion (PIR)",
    "Force / Flex",
    "Touch / Capacitive",
    "Rotary Encoder",
    "Thermistor - NTC",
    "Thermistor - PTC",
  ],
  Switches: [
    "Navigation / Joystick",
    "Push Button",
    "Tactile - SMD",
    "Tactile - Through-hole",
    "Slide Switch",
    "Toggle",
    "Rocker",
    "DIP Switch",
    "Rotary Switch",
    "Keyboard Switch",
    "Limit / Snap Action",
    "Reed Switch",
  ],
  "Thermal Management": [
    "Fan",
    "Heatsink",
    "Thermal Pad / Tape",
    "Thermal Paste",
    "Peltier / TEC",
  ],
  "Tools & Supplies": [
    "Solder / Flux",
    "Soldering Accessory",
    "Hand Tool",
    "Adhesive / Tape",
  ],
} as const;

export type ComponentCategory = keyof typeof CATEGORY_OPTIONS;

export const CATEGORY_KEYS: ComponentCategory[] = Object.keys(
  CATEGORY_OPTIONS,
).sort() as ComponentCategory[];
